{% set name = "r-xtensor" %}
{% set posix = 'm2-' if win else '' %}
{% set version = "0.14.1" %}
{% set sha256 = "0e5a0709dab0277f93ed2174f31efb4da4dab3e4f074c4ff009df10e09234dbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/Xtensor.R/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("c") }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - xtensor-r >=0.14.0,<0.15.0
  run:
    - r-base
    - {{ pin_compatible('xtensor-r', max_pin='x.x') }}

test:
  commands:
    - $R -e "library('xtensor')"           # [not win]
    - "\"%R%\" -e \"library('xtensor')\""  # [win]

about:
  home: http://github.com/xtensor-stack/Xtensor.R
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R bindings for xtensor, the C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor-r.readthedocs.io/
  dev_url: https://github.com/xtensor-stack/Xtensor.R

extra:
  recipe-maintainers:
    - conda-forge/r
    - SylvainCorlay
    - JohanMabille
    - wolfv
