appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FPN0cH6VFxqnLVlTg+o+R/sHfHpAzY4BBf+UHRgBRMz8SF9n2OUfD0Q9RFjjyOBQuhP9/E8g/bNgS6RAs1gaIF7dwV6CeABYFYYG63HdGcuikKfvJX7uJSwUHJ+Y2aW/e4uGvkbaxxSQTYXUl1esGADn006Zzhas5CeK+b0hlDX91QSZ8mtn4MrRa9XSz7qWP+Az9SPc1Esw2jEfW3QwU/pxNbdcngwvDBuLfYGTp6x3ixN0mmIxKkHY9YL5xpdYjzPqp5Llu6kzDPAh7i3L8n95uRBMNGptPg+z9R1AxlgfxD+wQsY6wfEZ3HYt1pnA4PfEBpwOAhQWSI+yVdXqihnfN+20tOaCk4hSX/yPeDT2PFabIVVl99D+NJZHZ/8jjQ+VJR3JwueV+/iG3+fd4giYKMtgMedLOV485XTcL7rucyETXOJPYzUw++19eq2jXMgqAV3c2AK3zSUbUGUjr2ULYZO/gq53rzyE8+zqOrDFKjpsdnurnuVJNkCSvBe4Pv6g9A10q3ByEra+hRBwwZ3AYLxF/RQCpuX9xP+wd3qNAGxubvu/18K8Cdg73cHXflijx6GnryPR5Kx/VeuPJR86dkzQ1HxKaUHnN8UVAPe+0NLcN1WNTk2wL7BssehQfzdVyk5y36k4UBszqi1bH4wzQZ87whbv/vMwfva4E+I=
conda_forge_output_validation: true
